export enum ConfigOptions {
    DB_DRIVER,
    DB_CONFIG,
    SOURCES_PATH,
    SOURCES_INCLUDE_ONLY,
    SOURCES_EXCLUDE,
    SAFFRON_MODE,
    WORKER_NODES,
    REQUEST_TIMEOUT,
    ARTICLE_AMOUNT,
    SCHEDULER_JOB_INT,
    SCHEDULER_JOB_HEAVY_INT,
    SCHEDULER_CHECKS_INT,
    GRID_DISTRIBUTED,
    MISC_LOG_LEVEL
}