export enum ConfigOptions {
    SOURCES_PATH,
    SOURCES_INCLUDE_ONLY,
    SOURCES_EXCLUDE,
    SAFFRON_MODE,
    WORKER_NODES,
    REQUEST_TIMEOUT,
    ARTICLE_AMOUNT,
    SCHEDULER_JOB_INT,
    SCHEDULER_JOB_HEAVY_INT,
    SCHEDULER_CHECKS_INT,
    GRID_DISTRIBUTED,
    GRID_PORT,
    MISC_LOG_LEVEL,
    DB_PUSH_ARTICLES,
    DB_GET_ARTICLES
}